# Generated by Django 6.0 on 2025-12-27 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_alter_hashtag_hashtag_name_alter_post_hashtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(blank=True, related_name='posts', to='social_app.hashtag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='people', to=settings.AUTH_USER_MODEL),
        ),
    ]
