# Generated by Django 6.0 on 2025-12-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_alter_post_hashtag_alter_review_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
